

DROP TABLE IF EXISTS Tareas;
DROP TABLE IF EXISTS CategoriasTarea;
DROP TABLE IF EXISTS Usuarios;
DROP TABLE IF EXISTS RolesUsuario;
DROP TABLE IF EXISTS Notas;
DROP TABLE IF EXISTS CategoriasNota;

CREATE DATABASE DevNotas;

CREATE TABLE RolesUsuario(
    idRolUsuario INT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    fechaCreacionRegistro DATE NOT NULL,

    CONSTRAINT pkRolUsuario PRIMARY KEY (idRolUsuario),
    CONSTRAINT uqNombreRolUsuarioUnico UNIQUE (nombre),
    CONSTRAINT ckActivoRolUsuario CHECK (activo IN (TRUE, FALSE))
);

CREATE TABLE Usuarios(
    idUsuario INT GENERATED BY DEFAULT AS IDENTITY,
    idRolUsuario INT NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    contraseñaHash TEXT NOT NULL,
    apellidoPaterno VARCHAR(70) NOT NULL,
    apellidoMaterno VARCHAR(70) NOT NULL,
    correoElectronico VARCHAR(200) NOT NULL,
    fechaNacimiento DATE NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    fechaCreacionRegistro DATE NOT NULL,

    CONSTRAINT pkUsuario PRIMARY KEY (idUsuario),
    CONSTRAINT fkUsuarioRolUsuario FOREIGN KEY (idRolUsuario) REFERENCES RolesUsuario(idRolUsuario),
    CONSTRAINT uqNombreUsuario UNIQUE (nombre),
    CONSTRAINT uqCorreoElectronicoUsuario UNIQUE (correoElectronico),
    CONSTRAINT ckActivoUsuario CHECK (activo IN (TRUE, FALSE))
);

CREATE TABLE CategoriasTarea(
    idCategoriaTarea INT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    fechaCreacionRegistro DATE NOT NULL,

    CONSTRAINT pkCategoriaTarea PRIMARY KEY (idCategoriaTarea),
    CONSTRAINT uqNombreCategoriaTareaUnica UNIQUE (nombre),
    CONSTRAINT ckActivoCategoriaTarea CHECK (activo IN (TRUE, FALSE))
);

CREATE TABLE Tareas(
    idTarea INT GENERATED BY DEFAULT AS IDENTITY,
    idCategoriaTarea INT NOT NULL,
    idUsuario INT NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    fechaInicio DATE NOT NULL,
    fechaFinalizacion DATE NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    fechaCreacionRegistro DATE NOT NULL,

    CONSTRAINT pkTarea PRIMARY KEY (idTarea),
    CONSTRAINT fkTareaUsuario FOREIGN KEY (idUsuario) REFERENCES Usuarios(idUsuario),
    CONSTRAINT fkTareaCategoriaTarea FOREIGN KEY  (idCategoriaTarea) REFERENCES CategoriasTarea(idCategoriaTarea),
    CONSTRAINT ckFechaFinalizacionTarea CHECK (fechaFinalizacion > fechaInicio),
    CONSTRAINT ckActivoTarea CHECK (activo IN (TRUE, FALSE))
);

CREATE TABLE CategoriasNota(
    idCategoriaNota INT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    fechaCreacionRegistro DATE NOT NULL,

    CONSTRAINT pkCategoriaNota PRIMARY KEY (idCategoriaNota),
    CONSTRAINT uqNombreCategoriaNotaUnica UNIQUE (nombre),
    CONSTRAINT ckActivoCategoriaNota CHECK (activo IN (TRUE, FALSE))
);

CREATE TABLE Notas(
    idNota INT GENERATED BY DEFAULT AS IDENTITY,
    idCategoriaNota INT NOT NULL,
    idUsuario INT NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    fechaCreacionRegistro DATE NOT NULL,

    CONSTRAINT pkNota PRIMARY KEY (idNota),
    CONSTRAINT fkNotaUsuario FOREIGN KEY (idUsuario) REFERENCES Usuarios(idUsuario),
    CONSTRAINT fkNotaCategoriaNota FOREIGN KEY (idCategoriaNota) REFERENCES CategoriasNota(idCategoriaNota),
    CONSTRAINT ckActivoNota CHECK (activo IN (TRUE, FALSE))
);

-- Procedimientos para RolesUsuario

CREATE OR REPLACE FUNCTION fn_listarRolesUsuario()
RETURNS TABLE (
    idRol INT,
    nombre VARCHAR(50),
    descripcion VARCHAR(250)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY 
    SELECT rol.idRolUsuario AS "idRolUsuario",
           rol.nombre AS "nombre",
           rol.descripcion AS "descripcion"
    FROM RolesUsuario AS rol
    WHERE rol.activo = TRUE;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_crearRolUsuario(
    p_nombre VARCHAR(50),
    p_descripcion VARCHAR(250)
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO RolesUsuario(nombre, descripcion, activo, fechaCreacionRegistro)
    VALUES (p_nombre, p_descripcion, TRUE, CURRENT_DATE);
    COMMIT;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_actualizarRolUsuario(
    p_nombre VARCHAR(50),
    p_descripcion VARCHAR(250),
    p_idRolUsuario INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE RolesUsuario
    SET nombre = p_nombre, descripcion = p_descripcion
    WHERE idRolUsuario = p_idRolUsuario;
    COMMIT;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_eliminarRolUsuario(
    p_idRolUsuario INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE RolesUsuario
    SET activo = FALSE
    WHERE idRolUsuario = p_idRolUsuario;
    COMMIT;
END;
$$;

-- Procedimientos para Usuario

CREATE OR REPLACE FUNCTION fn_listarUsuarios()
RETURNS TABLE (
    idUsuario INT,
    nombre VARCHAR(50),
    apellidoPaterno VARCHAR(70),
    apellidoMaterno VARCHAR(70),
    correoElectronico VARCHAR(200),
    fechaNacimiento DATE
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT usu.idUsuario AS "idUsuario",
           usu.nombre AS "nombre",
           usu.apellidoPaterno AS "apellidoPaterno",
           usu.apellidoMaterno AS "apellidoMaterno",
           usu.correoElectronico AS "correoElectronico",
           usu.fechaNacimiento AS "fechaNacimiento"
    FROM Usuarios AS usu
    WHERE activo = TRUE;
END;
$$;

